# Generated by Django 4.1.7 on 2023-03-22 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('commentary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['-id']},
        ),
    ]
