# Generated by Django 4.1.7 on 2023-04-25 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("commentary", "0003_alter_commentary_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Veröffentlicht"),
            preserve_default=False,
        ),
    ]
