# Generated by Django 4.1.7 on 2023-05-23 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commentary", "0004_commentary_published_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["-published_date", "-id"]},
        ),
    ]
