version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: feeder_database
      POSTGRES_USER: feeder_db_admin
      POSTGRES_PASSWORD: pw_feeder.db
    volumes:
      - ./var/db:/var/lib/postgresql/data