[tool.black]
line-length = 125
exclude = '''
(
  /(
      \.git
    | bin
    | venv
    | migrations
  )/
)
'''

[tool.isort]
force_alphabetical_sort_within_sections = true
force_single_line = true
from_first = false
known_first_party = "backend"
line_length = 125
lines_after_imports = 2
skip = "manage.py,wsgi.py,migrations"
skip_glob = "venv,bin"