# Generated by Django 4.1.7 on 2023-04-25 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0002_alter_feed_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Veröffentlicht"),
            preserve_default=False,
        ),
    ]
