# Generated by Django 4.1.7 on 2023-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_alter_user_birthdate_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AlterField(
            model_name="warn",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Falschinformationen", "Falschinformationen"),
                    ("Missbrauch von Privilegien", "Missbrauch von Privilegien"),
                    ("Belästigung", "Belästigung"),
                    ("Cybermobing", "Cybermobbing"),
                    ("Cybergrooming", "Cybergrooming"),
                    ("Whataboutismus", "Whataboutismus"),
                    ("Relativierung", "Relativierung"),
                    ("Erpressung", "Erpressung"),
                    ("Drohung", "Drohung"),
                    ("Wortwahl", "Wortwahl"),
                    ("Hassrede", "Hassrede"),
                    ("Beleidigung", "Beleidigung"),
                    ("Diskriminierung", "Diskriminierung"),
                    ("Sexismus", "Sexismus"),
                    ("Rassismus", "Rassismus"),
                    ("Faschismus", "Faschismus"),
                    ("Antisemitismus", "Antisemitismus"),
                    ("Betrug", "Betrug"),
                    ("Spam", "Spam"),
                ],
                default="Hassrede",
                max_length=30,
                verbose_name="Grund",
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
